version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hamamatsu-takeout-clawler"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-p3sxjqobfqxd"
s3_prefix = "hamamatsu-takeout-clawler"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

